\documentclass[10pt]{beamer}
\usetheme{Warsaw}
\usepackage{graphicx}
\usepackage[utf8]{inputenc}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage[notocbib]{apacite}


% rysunki
\usepackage{tikz}
\usepackage{ifthen}
\usepackage{xxcolor}
\usetikzlibrary{arrows}
\usetikzlibrary[topaths]
\usetikzlibrary{decorations.pathreplacing}


\begin{document}


<<knitrIntro, echo = FALSE, message=FALSE>>=
library(seqinr)
library(MASS)
library(xtable)
library(pROC)
load("prezent5_data.Rdata")
load("duration_signal_data.Rdata")
@


\date{}
\author{Michał  Burdukiewicz \inst{1} \and Piotr Sobczyk \inst{2} \and Paweł  Błażej \inst{1} \\ \and Paweł  Mackiewicz \inst{1}}
\institute[shortinst]{\inst{1} University of Wrocław, Department of Genomics, Poland \and %
\inst{2} Wrocław University of Technology, Institute of Mathematics and Computer Science, Poland}

\title{Signal peptide prediction using hidden Markov models}


\begin{frame}
\maketitle
\end{frame}

\begin{frame}
\frametitle{Outline}
\tableofcontents
\end{frame}


\AtBeginSection[]
{
\begin{frame}<beamer>
\frametitle{Outline}
\tableofcontents[currentsection]
\end{frame}
}




\section{Secretory signal peptides}

\begin{frame}
Secretory signal peptides:
\begin{itemize}
\item are short (20-30 residues) N-terminal sequences,
\item direct a protein to the endomembrane system and next to the extracellular localization,
\item possess three distinct domains, which lengths can vary from peptide to peptide~\cite{hegde_surprising_2006}.
\end{itemize}
\end{frame}

\begin{frame}
Proteins with secretory signal peptides:
\begin{itemize}
\item hormons (e.g., prolactin, glucagon),
\item immune system proteins (e.g., interferons, interleukins),
\item structural proteins (e.g., collagen),
\item metabolic enzymes (e.g., alpha-galactosidase, pepsins).
\end{itemize}
\end{frame}

\begin{frame}
\begin{figure}
<<echo = FALSE,fig.height=2.5,out.height=100>>=

plot(c(-0.2, 1.2), c(0.4,0.6), axes = FALSE, cex = 0, xlab = "", ylab = "",
     mar=c(0.1, 0.1, 0.1, 0.1))
rect(0, 0.4, 0.2, 0.6, border = NA, col = adjustcolor("blue", alpha.f = 0.30))
rect(0.2, 0.4, 0.6, 0.6, border = NA, col = adjustcolor("red", alpha.f = 0.30))
rect(0.6, 0.4, 0.85, 0.6, border = NA, col = adjustcolor("grey", alpha.f = 0.40))
rect(0.85, 0.4, 1.1, 0.6, border = NA, col = adjustcolor("green", alpha.f = 0.30))
text(0, 0.5, "N-", pos = 2, cex = 1.2, family = "mono")
text(1.1, 0.5, "-C", pos = 4, cex = 1.2, family = "mono")
text(0.1, 0.55, "n-region", pos = 1)
text(0.4, 0.55, "h-region", pos = 1)
text(0.725, 0.55, "c-region", pos = 1)
text(0.975, 0.55, "cleave site", pos = 1)
@
\end{figure}

n-region:
\begin{itemize}
\item usually 5-8 residues long,
\item mostly basic residues (histidine, arginine, lysine)~\cite{nielsen_prediction_1998}.
\end{itemize}
\end{frame}

\begin{frame}
\begin{figure}
<<echo = FALSE, fig.height=2.5, out.height=100>>=

plot(c(-0.2, 1.2), c(0.4,0.6), axes = FALSE, cex = 0, xlab = "", ylab = "",
     mar=c(0.1, 0.1, 0.1, 0.1))
rect(0, 0.4, 0.2, 0.6, border = NA, col = adjustcolor("blue", alpha.f = 0.30))
rect(0.2, 0.4, 0.6, 0.6, border = NA, col = adjustcolor("red", alpha.f = 0.30))
rect(0.6, 0.4, 0.85, 0.6, border = NA, col = adjustcolor("grey", alpha.f = 0.40))
rect(0.85, 0.4, 1.1, 0.6, border = NA, col = adjustcolor("green", alpha.f = 0.30))
text(0, 0.5, "N-", pos = 2, cex = 1.2, family = "mono")
text(1.1, 0.5, "-C", pos = 4, cex = 1.2, family = "mono")
text(0.1, 0.55, "n-region", pos = 1)
text(0.4, 0.55, "h-region", pos = 1)
text(0.725, 0.55, "c-region", pos = 1)
text(0.975, 0.55, "cleave site", pos = 1)
@
\end{figure}

h-region:
\begin{itemize}
\item usually 8-12 residues long,
\item strongly hydrophobic~\cite{nielsen_prediction_1998}.
\end{itemize}
\end{frame}

\begin{frame}
\begin{figure}
<<echo = FALSE, fig.height=2.5, out.height=100>>=

plot(c(-0.2, 1.2), c(0.4,0.6), axes = FALSE, cex = 0, xlab = "", ylab = "",
     mar=c(0.1, 0.1, 0.1, 0.1))
rect(0, 0.4, 0.2, 0.6, border = NA, col = adjustcolor("blue", alpha.f = 0.30))
rect(0.2, 0.4, 0.6, 0.6, border = NA, col = adjustcolor("red", alpha.f = 0.30))
rect(0.6, 0.4, 0.85, 0.6, border = NA, col = adjustcolor("grey", alpha.f = 0.40))
rect(0.85, 0.4, 1.1, 0.6, border = NA, col = adjustcolor("green", alpha.f = 0.30))
text(0, 0.5, "N-", pos = 2, cex = 1.2, family = "mono")
text(1.1, 0.5, "-C", pos = 4, cex = 1.2, family = "mono")
text(0.1, 0.55, "n-region", pos = 1)
text(0.4, 0.55, "h-region", pos = 1)
text(0.725, 0.55, "c-region", pos = 1)
text(0.975, 0.55, "cleave site", pos = 1)
@
\end{figure}

c-region:
\begin{itemize}
\item about 6 residues long,
\item a few polar, uncharged residues~\cite{jain_signal_1994}.
\end{itemize}
\end{frame}

\begin{frame}
\begin{figure}
<<echo = FALSE, fig.height=2.5, out.height=100>>=

plot(c(-0.2, 1.2), c(0.4,0.6), axes = FALSE, cex = 0, xlab = "", ylab = "",
     mar=c(0.1, 0.1, 0.1, 0.1))
rect(0, 0.4, 0.2, 0.6, border = NA, col = adjustcolor("blue", alpha.f = 0.30))
rect(0.2, 0.4, 0.6, 0.6, border = NA, col = adjustcolor("red", alpha.f = 0.30))
rect(0.6, 0.4, 0.85, 0.6, border = NA, col = adjustcolor("grey", alpha.f = 0.40))
rect(0.85, 0.4, 1.1, 0.6, border = NA, col = adjustcolor("green", alpha.f = 0.30))
text(0, 0.5, "N-", pos = 2, cex = 1.2, family = "mono")
text(1.1, 0.5, "-C", pos = 4, cex = 1.2, family = "mono")
text(0.1, 0.55, "n-region", pos = 1)
text(0.4, 0.55, "h-region", pos = 1)
text(0.725, 0.55, "c-region", pos = 1)
text(0.975, 0.55, "cleave site", pos = 1)
@
\end{figure}

Cleave site:
\begin{itemize}
\item very variable,
\item usually small, neutral residuals at -3 and -1 positions~\cite{nielsen_prediction_1998}.
\end{itemize}
\end{frame}

\begin{frame}
Patterns in the molecular structure of signal peptides allow creation of the heuristic algorithm identifying borders of all regions~\cite{nielsen_prediction_1998}.
\end{frame}


\section{Hidden semi-Markov model}

\begin{frame}
Hidden semi-Markov model of a secretory signal peptide:
\begin{itemize}
\item<1-> the observable distribution of amino acids is a result of being in a certain region (state),
\item<2-> a probability of staying in a given region decreases over time (reflects variability in regions' lengths).
\end{itemize}
\end{frame}

\begin{frame}
Training procedure:
\begin{itemize}
\item<1-> removal of atypical or poorly annotated records from data set of proteins with signal peptide from UniProt database,
\item<2-> determination of n-, h-, c-regions by the heuristic algorithm, 
\item<3-> reduction of dimensionality by aggregating amino acids to several physicochemical groups,
\item<4-> calculation of the amino acid group frequency in each region and the average length of the region,
\item<5-> training of HSMMs (model for signal peptide and model for protein without signal peptide).
\end{itemize} 
\end{frame}

\begin{frame}
<<echo = FALSE,message=FALSE,results='asis'>>=
tabAminokwasow = function(aminokwasy, nazwyGrupy, ...) {
  tab = cbind(data.frame(1:length(aminokwasy)), data.frame(sapply(aminokwasy, function(x) paste(x, collapse=", "))))
  dimnames(tab) = list(nazwyGrupy, c("Group", "Amino acids"))
  return(xtable(tab, align = c("r", "c", "l"), ...))
}

aa5 = list('1' = c("K", "R", "H"),
           '2' = c("V","I","L","M","F","W","C"),
           '3' = c("S", "T", "N", "Q"),
           '4' = c("D","E","A","P","Y","G"))
print(tabAminokwasow(aa5, c("Positively charged", "Nonpolar and aliphatic",
                            "Polar and uncharged", "Negatively charged and nonpolar"),
                     caption = "Classification of amino acids used by signal-hsmm."))
@
\end{frame}


\begin{frame}
During the test phase, each protein is fitted to two HSMMs. The outcome consists of probabilities of belonging to given models and predicted cleave site.
\end{frame}

\begin{frame}

\begin{figure}
\centering
\resizebox{9.5cm}{!}{%
\begin{tikzpicture}[->,>=stealth',shorten >=2pt,auto,node distance=3cm, thick]
  \tikzstyle{line} = [draw=black, color=blue!30!black!50, line width=1.5mm, -latex']
  \tikzstyle{main node} = [circle,fill=blue!20,draw, minimum size = 2.2cm, font=\itshape,
     align=center,  top color=white, bottom color=blue!50!black!70 ] %font=\sffamily\small\bfseries,
  %nodes
  \node[main node] 				 	(start') 	[]						{Start};	     
  \node[main node, bottom color=purple!70!black!70] 	(nregion') 	[right of=start',xshift=-5mm, yshift=15mm] 	{n-region};
  \node[main node, bottom color=pink!70!black!70] 	(hregion') 	[right of=nregion',xshift=-5mm,yshift=15mm] 	{h-region};
  \node[main node, bottom color=gray!70!black!70] 	(cregion') 	[right of=hregion',xshift=-5mm,yshift=-15mm] 	{c-region};
  \node[main node, bottom color=green!70!black!70] 	(mature') 	[right of=cregion',xshift=-5mm, yshift=-15mm] 	{Mature protein};
  
  %lines
  \path [line] (start')   edge node [left, color=black] {} (nregion');
  \path [line] (nregion') edge node [below, color=black] { } (hregion');
  \path [line] (hregion') edge node [below, color=black] { } (cregion');
  \path [line] (cregion') edge node [left, color=black] { } (mature');
  \draw [line] (start') to[out=340,in=200] (mature');
\end{tikzpicture} }
\end{figure}


\end{frame}

\section{signal.hsmm evaluation}

\begin{frame}
A validation data set contains 2288 proteins with experimentally confirmed signal peptides and 15238 proteins without signal peptides.
\\[12pt]
Proteins without known cleave site or with more than one cleave site were removed from the data set.
\end{frame}

\begin{frame}
Validation procedure:
\begin{enumerate}
\item<1-> sample without replacement 800 proteins with signal peptides an train signal-hsmm,
\item<2-> sample without replacement 100 proteins with signal peptides and 100 proteins without signal peptide and test it with newly trained signal-hsmm,
\item<3-> repeat above procedure 1000 times.
\end{enumerate} 
\end{frame}

\begin{frame}
<<echo = FALSE,message=FALSE,results='hide', fig.height=4.5>>=
plot(density(sapply(hundred_repsD, function(i) i$chars$auc)), main = "Density of AUC")
sapply(0:6*5, function(i)
  abline(h = i, col = "grey"))
sapply(45:50/50, function(i)
  abline(v = i, col = "grey"))
@
\end{frame}

\begin{frame}
<<echo = FALSE,message=FALSE,results='asis'>>=
aa2 = list('1' = c("G", "A", "P", "V", "L", "I", "M", "F"), 
           '2' =c("K", "R", "H"), 
           '3' =c("D", "E"), 
           '4' =c("S", "T", "C", "N", "Q", "Y", "W"))
nazwy2 = c("Nonpolar", "Polar (positive charge)", "Polar (negative charge)", "Polar")
print(tabAminokwasow(aa2, nazwy2, caption = "Classification of amino acids using only polarity and charge of a side chain."))
@
\end{frame}

\begin{frame}
<<echo = FALSE,message=FALSE,results='hide', fig.height=4.5>>=
plot(density(sapply(hundred_repsD, function(i) i$chars$auc)), main = "Density of AUC")
lines(density(sapply(hundred_repsD2[!wrongs], function(i) i$chars$auc)), col = "red")
legend("topleft", lty = 1, col = c("black", "red"), bg = "white",
       legend = c("Classification 1", "Classification 2"))
@
\end{frame}

\begin{frame}
<<echo = FALSE,message=FALSE,results='hide', fig.height=4.5>>=
all_cs <- do.call("rbind", lapply(hundred_repsD, function(i) i[["cs"]]))
all_cs2 <- do.call("rbind", lapply(hundred_repsD2[!wrongs], function(i) i[["cs"]]))
plot(density((all_cs[[1]] - all_cs[[2]])), main = "Density of cleave site misplacement")
sapply(-1:3*20, function(i)
  abline(v = i, col = "grey"))
sapply(1:4/20, function(i)
  abline(h = i, col = "grey"))

@
\end{frame}

\begin{frame}
<<echo = FALSE,message=FALSE,results='hide', fig.height=4.5>>=
plot(density((all_cs[[1]] - all_cs[[2]])), main = "Density of cleave site misplacement")
sapply(-1:3*20, function(i)
  abline(v = i, col = "grey"))
sapply(0:4/20, function(i)
  abline(h = i, col = "grey"))
lines(density((all_cs2[[1]] - all_cs2[[2]])), col = "red")
legend("topright", lty = 1, col = c("black", "red"), bg = "white",
       legend = c("Classification 1", "Classification 2"))
@
\end{frame}

\section{Comparision with other signal peptide predictors}

\begin{frame}
Other secretory signal peptide predictors:
\begin{itemize}
\item<1-> neural networks (SignalP 4.1)~\cite{petersen_signalp_2011},
\item<2-> hidden Markov models (Phobius)~\cite{kall_combined_2004},
\item<3-> position matrices (PredSi)~\cite{hiller_predisi:_2004}, 
\item<4-> optimized evidence theoretic K nearest neighbor (Signal-3L)~\cite{shen_signal-3l:_2007},
\item<5-> support vector machines~\cite{cai_support_2003}.
\end{itemize} 
\end{frame}

\begin{frame}
A data set chosen for comparison contains 70 proteins with experimentally confirmed signal peptides and 198 proteins without signal peptides.
\\[12pt]
Proteins without known cleave site or with more than one cleave site or added before 2012 were removed from the data set.
\\[12pt]
signal.hsmm was trained on data set of 2288 proteins with signal peptides.
\end{frame}

\begin{frame}
<<echo = FALSE,message=FALSE,results='hide', out.height=220, out.width=260,fig.align='center'>>=
pred_names <- c("signal.hsmm", "SignalP 4.1", "Phobius", "PredSi")
plot(roc(response = ets2, predictor = signalp4), col = "green", main = "ROC curve",
     ylim = c(0, 1), xlim = c(1, 0))
plot(signal_hsmmD[["roc"]], add = TRUE, col = "red")
plot(roc(response = ets2, predictor = phobius[, 1]), add = TRUE, col = "blue")
plot(roc(response = ets2, predictor = predsi[,4]), add = TRUE, col = "black")
legend("bottomright", lty = 1, col = c("red", "green", "blue", "black"),
       legend = pred_names)
@
\end{frame}

\begin{frame}
<<echo = FALSE,message=FALSE,results='hide', fig.height=4.5>>=
plot(roc(response = ets2, predictor = signalp4), col = "green", 
     ylim = c(0.8, 1), xlim = c(1, 0.8))
plot(signal_hsmmD[["roc"]], add = TRUE, col = "red")
plot(roc(response = ets2, predictor = phobius[, 1]), add = TRUE, col = "blue")
plot(roc(response = ets2, predictor = predsi[,4]), add = TRUE, col = "black")
legend("bottomright", lty = 1, col = c("red", "green", "blue", "black"),
       legend = pred_names)
@
\end{frame}

\begin{frame}
<<echo = FALSE,message=FALSE,results='asis'>>=
aucs <- c(signal_hsmmD[["auc"]],
          auc(response = ets2, predictor = signalp4),
          auc(response = ets2, predictor = phobius[, 1]),
          auc(response = ets2, predictor = predsi[, 4]))
dat <- data.frame(Predictor = pred_names, AUC = aucs)
print(xtable(dat, digits = 4))
@
\end{frame}

\section{Summary}

\begin{frame}
Hidden semi-Markov models can be used to accurately predict a presence of secretory signal peptides.
\\[12pt]
The prediction of cleavage site position still requires further refinement.

\end{frame}



\begin{frame}[allowframebreaks]
\bibliographystyle{apacite}
\bibliography{prez5}
\end{frame}

\end{document}