\documentclass[10pt]{beamer}
\usetheme{Warsaw}
\usepackage{graphicx}
\usepackage[MeX,T1,plmath]{polski}
\usepackage[cp1250]{inputenc}
\usepackage{indentfirst}
\usepackage[polish]{babel}
\selectlanguage{polish}
\usepackage{amsfonts}
\usepackage{amsmath}


\linespread{1.3}

\begin{document}
\SweaveOpts{concordance=TRUE}

<<knitrIntro, echo = FALSE, message=FALSE>>=
pdf.options(encoding = "CP1250")
library(seqinr)
library(MASS)
library(xtable)
library(rgl)

knit_hooks$set(rgl = function(before, options, envir) {
  if (!before) {
    ## after a chunk has been evaluated
    if (rgl.cur() == 0) return()  # no active device
    name = paste(options$fig.path, options$label, sep = '')
    rgl.snapshot(paste(name, '.png', sep = ''), fmt = 'png')
    return(paste('\\includegraphics[scale=0.37]{', name, '}\n', sep = ''))
  }
})
@


\date{}
\title{Predykcja lokalizacji subkom?rkowej}
\author{Micha? Burdukiewicz, Piotr Sobczyk}

\begin{frame}
\maketitle
\end{frame}


\begin{frame}
\tableofcontents
\end{frame}


\section{Przygotowanie danych}

\begin{frame}
Do stworzenia pierwszej wersji programu SignalP u?yto bazy Swiss-Prot 29 (czerwiec 1994) zawieraj?cej 38303 bia?ek.

\begin{block}{Zapytanie}
created:[1950 TO 1995] AND reviewed:yes
\end{block}

Powy?sze zapytanie znajduje 38440 bia?ek w bazie UniProt. 

Do uczenia programu SignalP wykorzystano tylko sekwencje z jednym, znanym miejscem ci?cia, dlatego ze zbioru znalezionych rekord?w  usuni?to te, w kt?rych informacja o peptydzie sygna?owym zawiera?a symbole:
 '<1', '?' oraz alternatywne miejsca ci?cia.

\end{frame}

\subsection{Sekwencje pochodzenia eukariotycznego}

\begin{frame}
Baza Swiss-Prot 29 po oczyszczeniu zawiera?a 2282 bia?ek eukariotycznych zawieraj?cych sekwencje sygna?owe sekrecji, kt?rych obecno?? potwierdzono eksperymentalnie.

Poni?sze zapytanie dalszym oczyszczeniu pozwala otrzyma? 2382 bia?ek:
\begin{block}{Zapytanie - eukarionty}
select: (keyword:signal) AND reviewed:yes AND created:[1950 TO 1995] AND taxonomy:'Eukaryota [2759]' AND annotation:(type:signal confidence:experimental)
\end{block}


\end{frame}

\subsection{Sekwencje pochodzenia prokariotycznego}

\begin{frame}
Baza Swiss-Prot 29 po oczyszczeniu zawiera?a 579 bia?ek prokariotycznych zawieraj?cych sekwencje sygna?owe sekrecji, kt?rych obecno?? potwierdzono eksperymentalnie. Ze zbioru ucz?cego wykluczono sekwencje odcinane przez peptydaz? sygna?ow? II.

Poni?sze zapytanie dalszym oczyszczeniu pozwala otrzyma? 603 bia?ka:
\begin{block}{Zapytanie - prokarionty}
select: (keyword:signal) AND reviewed:yes AND created:[1950 TO 1995] AND annotation:(type:signal confidence:experimental) NOT keyword:'Lipoprotein [KW-0449]' AND (taxonomy:'Bacteria [2]' OR taxonomy:'Archaea [2157]')
\end{block}


\end{frame}

\begin{frame}

NIE usuni?to sekwencji redundatnych, poniewa? nie by?o jasne w jaki spos?b dokonano tego podczas przygotowania zbioru ucz?cego dla programu SignalP.

\end{frame}

\section{Przyj?ty model}

\begin{frame}
\begin{figure}
<<sigseq, echo = FALSE, fig.height=2.5>>=

plot(c(-0.2, 1.2), c(0.4,0.6), axes = FALSE, cex = 0, xlab = "", ylab = "")
rect(0, 0.4, 0.2, 0.6, border = NA, col = adjustcolor("blue", alpha.f = 0.30))
rect(0.2, 0.4, 0.6, 0.6, border = NA, col = adjustcolor("red", alpha.f = 0.30))
rect(0.6, 0.4, 0.85, 0.6, border = NA, col = adjustcolor("grey", alpha.f = 0.40))
rect(0.85, 0.4, 1, 0.6, border = NA, col = adjustcolor("green", alpha.f = 0.30))
text(0, 0.5, "5'-", pos = 2, cex = 1.2, family = "mono")
text(1, 0.5, "-3'", pos = 4, cex = 1.2, family = "mono")
text(0.1, 0.55, "n-region", pos = 1)
text(0.4, 0.55, "h-region", pos = 1)
text(0.725, 0.55, "c-region", pos = 1)
text(0.925, 0.55, "ci?cie", pos = 1)
@
\end{figure}
\vspace{-1.5cm}
\begin{footnotesize}
\begin{itemize}
  \item n-region: 1-5 aminokwas?w, preferowane aminokwasy z dodatnim ?adunkiem.
  \item h-region: \textbf{\emph{0 - 20}} aminokwas?w, preferowane aminokwasy hydrofobowe.
  \item c-region: 3 - 7 polarnych aminokwas?w bez ?adunku.
  \item miejsce ci?cia: na pozycjach -3 i -1 w stosunku do miejsca ci?cia ma?e, oboj?tne aminokwasy.
\end{itemize}
\end{footnotesize}
\end{frame}



\subsection{Wyszukiwanie region?w n, h i c}

\begin{frame}
Wyznaczenie c-regionu:
\begin{itemize}
  \item z pozycji -1 przesun?? si? na pozycj? -3,
  \item przesuwa? si? do N-ko?ca do momentu napotkania bloku co najmniej dw?ch hydrofobowych aminokwas?w.
\end{itemize}

\begin{figure}
<<sigseqc, echo = FALSE, fig.height=2.5>>=

plot(c(-0.2, 1.2), c(0.4,0.6), axes = FALSE, cex = 0, xlab = "", ylab = "")
rect(0, 0.4, 0.2, 0.6, border = NA, col = adjustcolor("blue", alpha.f = 0.30))
rect(0.2, 0.4, 0.6, 0.6, border = NA, col = adjustcolor("red", alpha.f = 0.30))
rect(0.6, 0.4, 0.85, 0.6, border = NA, col = adjustcolor("grey", alpha.f = 0.40))
rect(0.85, 0.4, 1, 0.6, border = NA, col = adjustcolor("green", alpha.f = 0.30))

lines(c(0.6, 0.6), c(0, 1), col = "red", lwd = 2)

text(0, 0.5, "5'-", pos = 2, cex = 1.2, family = "mono")
text(1, 0.5, "-3'", pos = 4, cex = 1.2, family = "mono")
text(0.1, 0.55, "n-region", pos = 1)
text(0.4, 0.55, "h-region", pos = 1)
text(0.725, 0.55, "c-region", pos = 1)
text(0.925, 0.55, "ci?cie", pos = 1)
@
\end{figure}

\end{frame}

\begin{frame}
Wyznaczenie h-regionu:
\begin{itemize}
  \item przenie?? si? 6 aminokwas?w w stron? N-ko?ca bia?ka od 5'-ko?ca c-regionu, \emph{je?li pozycja osi?gni?ta w ten spos?b jest mniejsza ni? 1, to przenie?? si? do pierwszego aminokwasu i przej?? do kroku 3}.
  \item przesuwa? si? do N-ko?ca do momentu napotkania aminokwasu z ?adunkiem lub bloku co najmniej trzech niehydrofobowych aminokwas?w \emph{lub do momentu napotkania pierwszego aminokwasu}.
  \item je?li N-koniec h-regionu nie jest hydrofobowym aminokwasem, przesuwa? si? w stron? 3'-ko?ca do momentu napotkania hydrofobowego aminokwasu \textbf{lub pocz?tku c-regionu}.
\end{itemize}

\end{frame}


\begin{frame}
\begin{block}{Krok 1}
przenie?? si? 6 aminokwas?w w stron? N-ko?ca bia?ka od 5'-ko?ca c-regionu, \emph{je?li pozycja osi?gni?ta w ten spos?b jest mniejsza ni? 1, to przenie?? si? do pierwszego aminokwasu i przej?? do kroku 3}
\end{block}

Niekiedy pocz?tek c-regionu wyznaczany jest w okolicy pierwszego aminokwasu, wtedy za?o?enie o minimalnej d?ugo?ci 6 aminokwas?w h-regionu nie jest spe?nione.

\end{frame}

\begin{frame}

\begin{block}{Krok 2}
przesuwa? si? do N-ko?ca do momentu napotkania aminokwasu z ?adunkiem lub bloku co najmniej trzech niehydrofobowych aminokwas?w \emph{lub do momentu napotkania pierwszego aminokwasu}.
\end{block}

h-region mo?e by? tak kr?tki, ?e nie ma szansy na spe?nienie innego warunku ko?cz?cego ni? napotkanie pierwszego aminokwasu.

\end{frame}


\begin{frame}

\begin{block}{Krok 3}
je?li N-koniec h-regionu nie jest hydrofobowym aminokwasem, przesuwa? si? w stron? 3'-ko?ca do momentu napotkania hydrofobowego aminokwasu \textbf{lub pocz?tku c-regionu}.
\end{block}

Bez dodatkowego warunku pocz?tek h-regionu mo?e si? znajdowa? za pocz?tkiem c-regionu.

\end{frame}



\subsection{Zgodno??}

\begin{frame}

\begin{equation}
z = \sum_{i = 1}^{l} I(k_i = l_i)
\end{equation},

gdzie: $k$
\begin{itemize}
  \item $k$  - predykcja przynale?no?ci regionalnej z modelu teoretycznego,
  \item $l$  - predykcja przynale?no?ci regionalnej z ukrytego modelu markowa.
\end{itemize}
\end{frame}


\begin{frame}
Poprawi? te rysunki
\begin{figure}
<<dens, echo = FALSE, fig.height=4.5>>=
source(file="densities.Rdat")
par(mfrow=c(2,2), cex.main = 0.9, cex.lab = 0.8)
for (i in 1:4) {
titles <- c("Zgodno?? calkowita", "Zgodno?? - N-region", "Zgodno?? - H-region",
            "Zgodno?? - C-region")

dens_neg <- density(result_filtered_neg[i, ])
dens_pos <- density(result_filtered_pos[i, ])     
max_y <- ifelse(max(dens_neg[["y"]]) >= max(dens_pos[["y"]]), max(dens_neg[["y"]]), max(dens_pos[["y"]]))
plot(c(0, 1), c(0, max_y), main = titles[i], cex = 0, ylab = "G?sto??", xlab = "Zgodno??")
lines(dens_neg, lwd = 2)
lines(dens_pos, col = "red", lty = "dashed")
legend("topleft", c("neg", "pos"), lty = c("solid", "dashed"), lwd = c(2, 1), col = c("black", "red"))
}
par(mfrow=c(1,1), cex.main = 1.2, cex.lab = 1)
@
\end{figure}
\end{frame}

\begin{frame}
\begin{figure}
<<pca, echo = FALSE, fig.height=4.5,results='asis'>>=
source(file="dane_pca.Rdat")
library(xtable)
res_pc <- princomp(x = res[-5])
x <- res_pc
vars <- x$sdev^2
vars <- vars/sum(vars)
x <- res_pc
xtable(rbind(`Standard deviation` = x$sdev, `Proportion of Variance` = vars, 
        `Cumulative Proportion` = cumsum(vars)))



@
\end{figure}
\end{frame}

\begin{frame}
\begin{figure}
<<pca_plot, echo = FALSE, fig.height=4.5>>=

plot(res_pc$scores[, 1], res_pc$scores[, 2], cex = 0, xlab = "PCA_1", ylab = "PCA_2", main = "Wyniki PCA")
points(res_pc$scores[res[5] == "neg", 1], res_pc$scores[res[5] == "neg", 2])
points(res_pc$scores[res[5] == "pos", 1], res_pc$scores[res[5] == "pos", 2], col = "red")
@
\end{figure}
\end{frame}



\section{Zaproponowany algorytm}

\begin{frame}
\begin{itemize}
  \item na podstawie zbioru ucz?cego policzono cz?sto?ci wyst?powania aminokwas?w w r??nych regionach peptydu sygna?owego,
  \item dla ka?dego bia?ka w zbiorze walidacyjnych dla ka?dego potencjalnego miejsca ci?cia policzono zgodno?ci,
  \item na podstawie uzyskanych wynik?w nauczono SVM.
\end{itemize}
\end{frame}

\begin{frame}
\begin{figure}
<<roc, echo = FALSE, fig.height=4.5,message=FALSE>>=
load("pred.Rdat")
library(ROCR)
plot(performance(pred, "tpr", "fpr"), main = "ROC curve")
text(0.8, 0.2, paste0("AUC = ", round(performance(pred, "auc")@y.values[[1]], 2)))
@
\end{figure}
\end{frame}

\section{Wady SignalP 2}

\begin{frame}
Job rejected due to exceeded sequence limit.
There are currently a maximum of 2000 sequences, 4000 residues pr sequence and 200000 residues total 
that this server accepts in a single submission.Your submission had more residues, than allowed. 
Please try again with less input.
\end{frame}

\end{document}